import BST from './Node.js'

const root = new BST(50)
root.addNode(30)
root.addNode(20)
root.addNode(40)
root.addNode(80)
root.addNode(90)
root.addNode(650)
root.addNode(60)
root.addNode(50) // check
root.addNode(20)//check
root.addNode(1)
root.addNode(2)
root.addNode(10)
root.addNode(25)
root.addNode(0)

console.log('\n\n\nInOrder: ')
root.inOrder()
root.deleteNode(1)
root.updateNode(0, 100)
console.log('\n\n\nInOrder1: ')
root.inOrder()
root.deleteNode(50)
console.log('\n\n\nInOrder50: ')
root.inOrder()
root.deleteNode(5)
console.log('\n\n\nInOrder5: ')
root.inOrder()
root.deleteNode(2)
console.log('\n\n\nInOrder2: ')
root.inOrder()
console.log('\n\n\nPostOder: ')
root.postOrder()